### PR TITLE
Ignore expired vouchers because basket also ignores them.

### LINKED ISSUE #3216: Vouchers that have expired since adding cause error without explanation on order creation
While the basket ignores vouchers that are expired since the order was created, the OrderPlacementMixin raises an error with an empty explanation.

### PR DESCRIPTION
**Pull request by specialunderwear**
If not the order placement fails with an empty error message.

fixes #3216

### CODE REVIEW

**Comment by solarissmoke** [comment]
Is there an edge case here where the order total was determined before the voucher expired? In which case the total will be wrong? I feel like it would be better in this case to (a) remove expired vouchers from the basket (or report an error there) as soon as they are detected, and throw an error during order creation.

**Comment by specialunderwear** [comment]
I added a test and that test fails without the fix.

**Comment by solarissmoke** [comment]
@specialunderwear I'm not disputing that your changes fix the test you have added. 

What I am saying is that I think this introduces the possibility that Oscar can create an order whose totals are invalid, because they include a discount from a now-removed voucher. I am not convinced that the correct behaviour is to silently ignore the voucher at this stage (because it could have been valid when the order totals were calculated). Doesn't it make more sense to report a more meaningful error here?

**Comment by specialunderwear** [comment]
It can happen only if a voucher expires during the request after computing the basket total.

**Pull request merged**
