### PR TITLE
Add Python 3.10 to test suite

### PR DESCRIPTION
**Pull request by crgwbr**

### CODE REVIEW

**Review by sasha0 — APPROVED** [review]
Looks good for me.

**Review by sasha0 — CHANGES_REQUESTED** [review]
Looks good, but please rebase remote branch against master and resolve conflicts.

**Review by joeyjurjens — DISMISSED** [review]

**Comment by crgwbr** [comment]
> Looks good, but please rebase remote branch against master and resolve conflicts.

Just rebased these changes again. Any chance we can get this merged soon?

**Comment by jayvdb** [comment]
ping @sasha0

**Review by jayvdb — APPROVED** [review]

**Review by viggo-devries — APPROVED** [review]

**Review by viggo-devries — APPROVED** [review]

**Comment by viggo-devries** [comment]
Rebased these changes into: #4098 so we can test everything against python 3.10 before merging into main

**Pull request closed without merging**
