### PR TITLE
Use treebeard 3.0 which silences Django 1.7 warnings

### PR DESCRIPTION
**Pull request by mvantellingen**

### CODE REVIEW

**Comment by mbertheau** [comment]
Woohoo! :)

**Comment by codeinthehole** [comment]
Does this have any backwards compatibility implications? Can we continue to support Django 1.6.x for Oscar 1.1?

**Comment by mvantellingen** [comment]
It should still support Django 1.6, as far as I can tell it's mostly a release to make it compatible with Django 1.7+

See https://github.com/tabo/django-treebeard/blob/master/CHANGES

**Comment by clintonb** [comment]
Any idea when this change will be released? It didn't make 1.0.2.

**Comment by clintonb** [comment]
Never mind. I just saw the milestone.

**Pull request merged**
