### PR TITLE
Split oscar.test.newfactories in multiple modules

### PR DESCRIPTION
**Pull request by mvantellingen**
Create a factory module per app and move them under the new
oscar.test.factories module.

### CODE REVIEW

**Comment by mbertheau** [comment]
LGTM. I'd consolidate the imports - we do

```python
from oscar.test import factories
from oscar.test.factories import (
     BenefitFactory, ConditionalOfferFactory, ConditionFactory, RangeFactory)
```

in some modules. The first import should be removed.

**Comment by mvantellingen** [comment]
Ok! I'll merge this and go through the code after that to fix all import statements

**Comment by mvantellingen** [comment]
Or in retrospect, i'll fix it in this PR ;-)

**Comment by mvantellingen** [comment]
Merged

**Pull request closed without merging**
