### PR TITLE
Issue/675/per variant image support

### PR DESCRIPTION
**Pull request by john-parton**
## Summary ##
* Should close https://github.com/django-oscar/django-oscar/issues/1611
* Working towards https://github.com/django-oscar/django-oscar/issues/675

### Changes ###
* Enable association of variants with specific images
    * New `ManyToMany` relationship
    * Dashboard integration
    * Basket integration (show correct thumbnail)
    * `ProductDetailView` integration
* `AddToBasketForm` has been modified to better reflect how a user interacts with it
    * When a user views a variant, the other 'siblings' are displayed in the form
    * Form uses `AdvancedRadioSelect` instead of `AdvancedSelect`, and wraps the choices in links to the actual variant pages
    * `child_id` hack has been removed, replaced with more explicit `ModelChoiceField`
    * `AdvancedSelect` widgets has been enhanced so that disabled values do not have to be pre-computed and passed to the constructor, but rather passed along with choices (details in source)
    * `AdvancedChoice` and `DisabledChoice` helper classes to define disabled options
    * More options for `AdvancedSelect`: `AdvancedRadioSelect`, `AdvancedSelectMultiple`, `AdvancedCheckboxSelectMultiple`
* `ProductDetailView` now returns a full page for a variant
    * The plan is to add in a progressive enhancement, so we can do an AJAX request to that URL endpoint, and get some HTML fragments or some JSON representing the variant

### Weak points / To-do ###
* The UI for associating images with variants is currently a little clunky. 
* Associating variants with images is currently pretty tedious, maybe find some way to streamline it
* Currently doesn't include a progressive enhancement for making variant selection simpler
* Documentation & Tests
* The UI still doesn't allow the user to drill down by "dimensions" (e.g. Color, Size, Flavor, etc.), and fundamentally still presents the variants in a flat fashion

#### PS ####
I'm planning on making regular contributions to Oscar. Please let me know if there's anything I can do to make this process better!

John P.

### CODE REVIEW

**Comment by john-parton** [comment]
I based this on releases/1.0. Should the PR be against master? Should PRs always be against master?

Sorry if this is wrong or annoying; I'm just trying to get the basics down so that I can actually be helpful.

Thanks

**Comment by mvantellingen** [comment]
No worries, glad to help. IMHO the best is to submit pull requests against master and then we can decide what needs to be backported to the 1.0 branch.

**Comment by john-parton** [comment]
Good to know. So, should I go ahead and re-submit it against master?

Thanks,
John

**Comment by john-parton** [comment]
I resubmitted this as https://github.com/django-oscar/django-oscar/pull/1643

Please close this PR.

Thanks

**Comment by mvantellingen** [comment]
Close as requested

**Pull request closed without merging**
