### PR TITLE
Feature/voucher sets

### PR DESCRIPTION
**Pull request by pjstevns**
Code ported from contribution by @mvantellingen 

Adds support for managing large amounts of vouchers grouped in sets.

### CODE REVIEW

**Comment by sasha0** [comment]
Please rebase remote branch and resolve conflicts.

**Comment by pjstevns** [comment]
rebased and pushed

**Comment by sasha0** [comment]
Now it needs to re-generate migrations due to the conflict.

**Comment by pjstevns** [comment]
regenerated migrations

**Comment by sasha0** [comment]
Looks good in general, just needs at least some documentation of voucher set purpose and usage. Would you add it?

**Comment by pjstevns** [comment]
Oscar seems to lack such documentation generally - at least I couldn't find much, but I've added some explainations in the model and rst file for vouchers.

**Comment by sasha0** [comment]
Thanks. It looks good now.

**Pull request merged**
