### PR TITLE
Added support package for Oscar

### PR DESCRIPTION
**Pull request by SalahAdDin**
I' adding this package because after a very hard week work i got update the entire package for a usable software.
Also i want you or whatever other people help me to finish his features and improve it because i can't do it alone(it could begins solving type erros and documentation missings).

Thank you very much.

### CODE REVIEW

**Comment by solarissmoke** [comment]
These should be added to the "community maintained packages" section that appears below this one, rather than the "stable and ready for use" section. Please amend and then we'll merge.

**Comment by SalahAdDin** [comment]
Ok, i will see it.

**Comment by SalahAdDin** [comment]
@solarissmoke I can't find these section.

**Comment by SalahAdDin** [comment]
Thank you!

**Pull request merged**
