### PR TITLE
Fix Catalogue Migrations

### PR DESCRIPTION
**Pull request by kooba**
This PR will turn off `db_constraint` on `productimage.product` foreign key  before removing unique constraint and put it back on after unique constraint is removed. 

This has been reported on https://github.com/django-oscar/django-oscar/issues/2554 and seems to be related to https://bugs.mysql.com/bug.php?id=37910

It seems to affect MySQL only but the change should not negatively affect other engines.

### CODE REVIEW

**Comment by solarissmoke** [comment]
Thanks for figuring out what the issue is here. I think this patch looks good, but it highlights the fact that we don't run tests on MySQL. I am going to try and add MySQL to the test matrix before we merge this so that we can verify it fixes the issue canonically.

**Comment by sasha0** [comment]
@solarissmoke for what Python/Django version do you want to add MySQL?

**Comment by solarissmoke** [comment]
I was just going to add it for the whole matrix. We should be testing every version that we support with MySQL.

**Comment by sasha0** [comment]
@kooba have you encountered also unicode/concurrency issues with MySQL? We tried to add MySQL to our testing matrix and found out them - https://github.com/django-oscar/django-oscar/pull/2630.
Thanks.

**Comment by kooba** [comment]
@sasha0 I have not encountered these issues myself yet, but my project is still in infancy stage. I'll try to look at https://github.com/django-oscar/django-oscar/pull/2630 to see if I can help.

**Comment by craigloftus** [comment]
We don't support mysql currently, so closing for now.

**Pull request closed without merging**
