### PR TITLE
Feature/django 110

### PR DESCRIPTION
**Pull request by hdknr**
oscar.apps.shipping.WeightBased

### CODE REVIEW

**Comment by mvantellingen** [comment]
Thanks, @pxg is also workin on this and there is also this #2055 PR from me. Would be cool if all branches can be merged / combined effort

**Comment by pxg** [comment]
Hi @hdknr I have been looking at getting Django 1.10 support for Oscar. The main issue I've found (as I'm sure you've noticed too) is many of the tests fail.

**Comment by mvantellingen** [comment]
@pxg my branch fixed all issues except those related to the subfieldbase iirc

**Comment by pxg** [comment]
@mvantellingen ok cool, I didn't realise you'd fixed all the other stuff! I'm happy to merge everything into a combined branch.

**Comment by SalahAdDin** [comment]
@pxg @mvantellingen Thank you very much guys.

**Comment by mvantellingen** [comment]
Added 1.10 via another PR in master. Thanks for the PR though, really appreciated.

**Pull request closed without merging**
