### PR TITLE
add public products to ProductLookupView queryset

### PR DESCRIPTION
**Pull request by xplsek03**

### CODE REVIEW

**Comment by specialunderwear** [comment]
Could you please add 1 test demonstrating that currently this functionality is broken, and you have fixed it?

**Comment by xplsek03** [comment]
> Could you please add 1 test demonstrating that currently this functionality is broken, and you have fixed it?

100%, just gotta take some time, very busy now

**Review by specialunderwear — CHANGES_REQUESTED** [review]
please add tests demonstrating the issue

**Comment by samar-hassan** [comment]
@xplsek03  Can you please explain the reason for adding each variant individually to the recommended products dropdown list? Currently we just show the parent or standalone products. Although for parent products we are redirected to a separate page and there we have to select the variant to add to our basket. I guess you may want to avoid such behavior and display just a specific variant in the recommendations so that it can be added without additional steps.

**Comment by xplsek03** [comment]
> @xplsek03 Can you please explain the reason for adding each variant individually to the recommended products dropdown list? Currently we just show the parent or standalone products. Although for parent products we are redirected to a separate page and there we have to select the variant to add to our basket. I guess you may want to avoid such behavior and display just a specific variant in the recommendations so that it can be added without additional steps.

Overflown with another projects. Will have to get to oscar again for next proj.

**Pull request closed without merging**
