### PR TITLE
Fix approved product review queryset

### LINKED ISSUE #395: Create template tag for reviews
See https://github.com/tangentlabs/django-oscar/commit/6029026b7585f14bd88bfe33d4b4b296f3f7d14b#commitcomment-2209224

It makes more sense to have reviews loaded via a templatetag rather than in the ``get_context_data`` method.

### PR DESCRIPTION
**Pull request by sasha0**
Fixes #395

### CODE REVIEW

**Comment by mvantellingen** [comment]
I've solved it locally using the following construct:

class ProductReviewQuerySet(models.QuerySet):
    use_for_related_fields = True

    def approved(self):
        return self.filter(status=self.model.APPROVED)


class AbstractProductReview:
    # ...
    objects = ProductReviewQuerySet.as_manager()
    # ...

This way we can use product.reviews.approved().all(). IMHO a cleaner way

**Comment by sasha0** [comment]
@mvantellingen yeah, agree. I'll rework PR.

**Comment by sasha0** [comment]
@mvantellingen done - reworked and added test.

**Comment by mvantellingen** [comment]
Nice! It does break backwards compatibility by removing the `approved` manager. We might get away with a message in the release notes?

**Comment by sasha0** [comment]
@mvantellingen Mb we could firstly merge you PR #1919 and then I'll update release notes?

**Comment by mvantellingen** [comment]
Done :-)

**Comment by sasha0** [comment]
@mvantellingen done too :-).

**Comment by sasha0** [comment]
@maikhoepfel @mvantellingen already updated PR, please take a look.

**Comment by mvantellingen** [comment]
Hi @sasha0 sorry for not looking faster at this. Could you update the PR with changes to 1.3? We can finally release this since our dependencies are now all 1.9 compatible

**Comment by mvantellingen** [comment]
Rebased and merged

**Pull request closed without merging**
