### PR TITLE
[WIP] Start of implementation of a new dashboard

### PR DESCRIPTION
**Pull request by mvantellingen**
This PR tries to introduce a new modern dashboard for Oscar. It will still be using bootstrap 3 so that custom dashboard's views will still be functional.

If you want to help then please check our slack channel #dashboard (via https://slack.oscarcommerce.com)

See http://oscar.mvantellingen.nl/order_detail.html for some work in progress look and feel

Todo:
 - [ ] Improve the sidebar
 -  [ ] Update pages for catalogue
 -  [ ] Update pages for orders (mvantellingen)
 -  [ ] Update pages for pages
 -  [ ] Update pages for partners
 -  [ ] Update pages for promotions
 -  [ ] Update pages for ranges
 -  [ ] Update pages for reports
 -  [ ] Update pages for reviews
 -  [ ] Update pages for users
 -  [ ] Update pages for vouchers
 -  [ ] Improve webpack config

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
I want report some bugs:
screenshot_20170418-184113
screenshot_20170418-183836
screenshot_20170418-184035

Other horrible bug: clicking menu items doesn't change between different views,all time shows the initial changed view.

**Comment by sasha0** [comment]
Thanks for taking look, however new dashboard layout is at the early beginning and not ready for testing yet.

**Comment by Belonias** [comment]
Would be nice if the tree would apply on product categories etc.

**Comment by solarissmoke** [comment]
I'm going to close this because there's been no activity for 3 years, and the initial work done here has major conflicts with the WIP port to Bootstrap 4, as well as a new approach to asset management. If we do want to redesign the dashboard we're going to have to start afresh.

**Pull request closed without merging**
