### PR TITLE
Transform Emails with Premailer

### PR DESCRIPTION
**Pull request by alexphelps**
This is a followup on #2317 to implement `premailer` to inline the css for email client compatibility as recommended by [mailgun](http://blog.mailgun.com/transactional-html-email-templates/).

### CODE REVIEW

**Comment by alexphelps** [comment]
@sasha0 Please review and let me know if you think this needs anything else before being considered for merging.

**Comment by sasha0** [comment]
I investigated a way to introduce `premailer` within the PR #2317 and faced the issue with `base_url` - https://github.com/django-oscar/django-oscar/pull/2317#issuecomment-347895085. `premailer` determines local static path as absolute - due to the leading slash and tries to load it as is.  Providing `base_url` explicitly didn't look as a good idea - premailer then would try to download the file, rather then just process it.

**Comment by alexphelps** [comment]
@sasha0 the way that I've added premailer doesnt require a base_url due to the CSS being inline in a `<style></style>` block and not being in an external file which follows the basic example [here](https://github.com/peterbe/premailer).

I'm still not quite understanding the external CSS file or why one would implement an email with one  given that external CSS is not supported by email. One option with django templates is to create a template partial with the email css inside of a `<style></style>` block that can be included in the template with would be processed by premailer when the template is compiled. 

@craigloftus I agree on adding the option to disable it.

**Comment by sasha0** [comment]
> I'm still not quite understanding the external CSS file or why one would implement an email with one given that external CSS is not supported by email. 

External CSS can be used only in conjunction with Premailer - e.g. you don't need to place inline styles in the `<style></style>` tags - Premailer would fetch and process all for you. Although due to the complications, I mentioned in the comment above https://github.com/django-oscar/django-oscar/pull/2590#issuecomment-364454356, it's not easily possible to achieve now.

I took a look at the code again and agree with @craigloftus. So, please rebase remote branch, resolve conflicts, adjust PR due to the feedback above and mention about this change in the release notes.

Thanks.

**Comment by SalahAdDin** [comment]
@alexphelps did you?

**Comment by alexphelps** [comment]
@SalahAdDin Sorry, havent had time to get back to this. We are using premailer internally on our project now but haven't time to get back to creating a stronger solution to be able to add it to oscar. 

The solution we are using does not use an external file as mentioned, trying to use an external file will cause issues.

Our email base.html template pulls in the css as a jinja template include like this
```
<style>
  {% include "customer/emails/partials/styles.css" %}
</style>
```

Now the CSS is inline in the head, then premailer can transform the html to inline all the styles as so. 
```
from premailer import transform
messages['html'] = transform(messages['html'])
```

**Pull request closed without merging**
