### PR TITLE
update django-widget-tweaks version

### PR DESCRIPTION
**Pull request by slav0nic**
django-widget-tweaks 1.3 doesn't work correct with django 1.8

### CODE REVIEW

**Comment by kunkku** [comment]
Please merge #1793 before this if you really want to use version 1.4.

@slav0nic: As you authored the respective commit in django-widget-tweaks, could you please explain why it is essential to deepcopy the fields? I can run Oscar with version 1.3 just fine on Django 1.8. Using deepcopy makes things fail in ways that are unpredictable and hard to debug as demonstrated by the aforementioned pull request.

Moreover, django-widget-tweaks has less than 200 LOC. My fear is that we end up writing more lines of boilerplate code to avoid the problems caused by deepcopy.

**Comment by slav0nic** [comment]
you can run test for 1.3 version with django 1.8 and check issue https://bitbucket.org/kmike/django-widget-tweaks/issue/17/django-18-and-append_attr

**Comment by kunkku** [comment]
I did some testing and it seems shallow copying suffices (https://github.com/kmike/django-widget-tweaks/pull/18).

**Comment by slav0nic** [comment]
1.4.1 version released without `copy`, sorry for this)

**Comment by mvantellingen** [comment]
@slav0nic so we need a minimum of 1.4.1?

**Comment by slav0nic** [comment]
yes

**Comment by mvantellingen** [comment]
Ok, i've committed it. Thanks :-)

**Pull request closed without merging**
