### PR TITLE
update README.rst, add django-oscar-saferpay

### PR DESCRIPTION
**Pull request by yvess**
I added django-oscar-saferpay (payment integration) to the README.rst, section community extensions

### CODE REVIEW

**Comment by sasha0** [comment]
Not sure if the package is ready to use already - it provides transaction list and detail views for the dashboard for saferpay payments and provides checkout integration in the readme. Please see https://github.com/django-oscar/django-oscar-docdata for the reference.

**Comment by yvess** [comment]
The heavy lifting part is in [django-saferpay](https://github.com/taywa/django-saferpay) django-oscar-saferpay is only the dashboard part and the oscar specific documentation. I separated it so that django-saferpay can also be used for other projects without the oscar dependency. It's already used in a production. I made the readme link to django-saferpay more visible.

**Comment by sasha0** [comment]
> The heavy lifting part is in django-saferpay django-oscar-saferpay is only the dashboard part and the oscar specific documentation.

That's the thing - `django-oscar-saferpay` could have Saferpay integration into the checkout and etc, described by you in the Readme, directly in the codebase, so that user won't have to copy-paste it.

**Comment by sasha0** [comment]
Due to the lacking feedback from the author and considering my comments above are still relevant (package does not provide any integration in the codebase, but suggests it in the README), I'm inclined to close this PR, but would like to know your opinion on that @solarissmoke

**Comment by yvess** [comment]
No problem, I will close the PR. Perhaps I will create some day a "proper" package, but not sure if/and when I will do it. I had the perception that you almost always need to customise it, so I focused on documenting that part.

**Pull request closed without merging**
