### PR TITLE
Bug AbsoluteDiscountBenefit

### PR DESCRIPTION
**Pull request by ebottos94**
Hi, according with the description in the class AbstractBenefit in file src/oscar/apps/offer/abstract_models.py in line 480, for the absolute discount the discount's logic is : "Discount is a fixed amount off of the product's value". 

In the file src/oscar/apps/offer/benefits.py instead the logic in the class AbsoluteDiscountBenefit is developed as if the discount were "Discount is a fixed amount off of the total amount of the shopping".

I assumed that the description "Discount is a fixed amount off of the product's value" is correct and i've change the AbsoluteDiscountBenefit's code so that it works as the description would like.

Thanks.

### CODE REVIEW

**Comment by specialunderwear** [comment]
Hi, I think you better improve the description, because what you are doing now is change exsiting offers on sites that use this functionality. I think most customers would not enjoy it when suddenly their offers give a much larger discount then before after an update!

**Comment by ebottos94** [comment]
@specialunderwear yes I've thought that but the description of the offer is enough clear now, so i don't think that the customers use this offer now. But you are rigth. Anyway, now the description does not reflect the logic, so if you don't want change the logic I think that the description must be changed!

**Comment by specialunderwear** [comment]
Yes, hence is suggest improving the description.

**Review by specialunderwear — CHANGES_REQUESTED** [review]
We can't change the logic, because that would change working of the offer in existing sites. So please change the description. If you do need the different functionality, I suggest adding a new type of offer that implements that.

**Comment by viggo-devries** [comment]
@samar-hassan I think you need to edit a migration because the make migration test failed now.

**Comment by viggo-devries** [comment]
@samar-hassan please edit the existing migration, a new migration for choices is not needed!

**Review by viggo-devries — APPROVED** [review]

**Pull request merged**
