### PR TITLE
Solr: restore price range in search facets

### PR DESCRIPTION
**Pull request by gwaidacher**
see #4375 

Solr expects "price_exact", so if `is_solr_supported()`, just the query param is altered to `price_exact`, the field name in facet date remains `price`

### CODE REVIEW

**Comment by gwaidacher** [comment]
How can I fix the `INTERNALERROR> AttributeError: 'Settings' object has no attribute 'STORAGES'`?

**Comment by viggo-devries** [comment]
> How can I fix the `INTERNALERROR> AttributeError: 'Settings' object has no attribute 'STORAGES'`?

Maybe try rebasing your branch? I think something was merged that fixes this error.

**Comment by gwaidacher** [comment]
> > How can I fix the `INTERNALERROR> AttributeError: 'Settings' object has no attribute 'STORAGES'`?
> 
> Maybe try rebasing your branch? I think something was merged that fixes this error.

I rebased twice, including your yesterday commit, another Error occurred:

FAILED tests/unit/customer/test_forms.py::TestOrderSearchForm::test_orders_descriptions - AssertionError: False is not true

**Comment by gwaidacher** [comment]
> > How can I fix the `INTERNALERROR> AttributeError: 'Settings' object has no attribute 'STORAGES'`?
> 
> Maybe try rebasing your branch? I think something was merged that fixes this error.

I had to fix the last two tests in [tests/unit/customer/test_forms.py](https://github.com/django-oscar/django-oscar/pull/4376/files#diff-736e54ba7b7fb73d5ae58400bdde59120226f9453a98a7c4c5df0a5948f6488d) which did not succeed. Please have a look.

**Pull request merged**
