### PR TITLE
How about this pinning strategy?

### PR DESCRIPTION
**Pull request by specialunderwear**
How about making defensive pinning optional, but the default in the documentation?

### CODE REVIEW

**Comment by solarissmoke** [comment]
As the person who currently responds to the majority of support requests, I don't think that defaulting to unpinned is a good idea. I think the default needs to be pinned, with an option to use `unsafe` dependencies if you want to. Otherwise every newbie who installs Oscar without reading the documentation is going to start with a broken installation, and we will be inundated with support issues.

No issues with doing it the other way around though.

**Comment by specialunderwear** [comment]
The other way around does not work.

**Comment by solarissmoke** [comment]
In that case IMHO, this isn't a good idea. Doing `pip install django-oscar` will almost certainly result in unsupported dependencies being installed (hence why the tests fail on this PR), which I don't think is a good experience for a first time installer.

If it's really an issue for you then perhaps a fork which doesn't pin dependencies is a better option?

**Comment by specialunderwear** [comment]
I tried and because they are extras they don't override so you can not remove a defensive pinning.

**Comment by solarissmoke** [comment]
Closing in favour of discussion on #2797.

**Pull request closed without merging**
