### PR TITLE
Upgrade Bootstrap to 3.4.1.

### PR DESCRIPTION
**Pull request by sasha0**

### CODE REVIEW

**Comment by solarissmoke** [comment]
@sasha0 you need to recompile assets - these are committed.

**Comment by sasha0** [comment]
@solarissmoke indeed, thanks.

**Comment by solarissmoke** [comment]
@sasha0 I think this needs to be backported to 1.6.x seeing as it is a security release?

Also I'd suggest that as a matter of best practise we get at least one person to review PRs before they are merged? Does that sound OK to you?

**Comment by sasha0** [comment]
> @sasha0 I think this needs to be backported to 1.6.x seeing as it is a security release?

Yep. I'll backport soon, so you cat cut a release.

> Also I'd suggest that as a matter of best practise we get at least one person to review PRs before they are merged? Does that sound OK to you?

Agree for the most cases, but we can take this discussion into the Slack.

**Comment by SalahAdDin** [comment]
Do you have planned to upgrade to Bootstrap 4?

**Pull request merged**
