### PR TITLE
project contribution section and code of conduct

### PR DESCRIPTION
**Pull request by brahim12chamakh**

### CODE REVIEW

**Review by viggo-devries — CHANGES_REQUESTED** [review]
please add emails

**Comment by viggo-devries** [comment]
We also have this: https://django-oscar.readthedocs.io/en/latest/internals/contributing/index.html

maybe you can implement this this link.

**Comment by brahim12chamakh** [comment]
i added the emails

**Comment by specialunderwear** [comment]
thank you!

**Pull request merged**
