### PR TITLE
Create simple dockerfile to run the sandbox

### PR DESCRIPTION
**Pull request by mvantellingen**
This is still really basic (we can add elasticsearc etc in the future).

### CODE REVIEW

**Comment by sasha0** [comment]
@mvantellingen we had actually another similar PR in progress - #1366 .

**Comment by mvantellingen** [comment]
@sasha0 Yeah I remember. Looking at that PR again it seems to do too much, I think we should just use this as a starting point and add improvements along the way.

**Comment by mvantellingen** [comment]
Also perhaps good to mention is that one of the reasons I've added it is that we might want to run http://latest.oscarcommerce.com/ via the docker instance. It seems it is still running an old version.

Automatically building the sandbox via docker hub and deploying it somewhere might result in a simple to manage workflow.

**Comment by mvantellingen** [comment]
Images of this branch are now automatically build and published at https://hub.docker.com/r/oscarcommerce/django-oscar-sandbox/

Simply run via:

    docker run -p 8080:8080  oscarcommerce/django-oscar-sandbox

**Pull request merged**
