### PR TITLE
DRAFT: GitHub Actions: Test on Python v3.12 and Django v5.0

### PR DESCRIPTION
**Pull request by cclauss**
Blocked by:
* django-haystack/django-haystack#1863
    * https://pypi.org/project/django-haystack -- Need a version later than v3.2.1

Many of the GitHub Actions changes will be fixed automatically by:
* #4230

### CODE REVIEW

**Comment by viggo-devries** [comment]
@cclauss the tests and pylint don't pass right now.

**Comment by cclauss** [comment]
Are they fixed or not yet?

**Comment by cclauss** [comment]
The tests and pylint pass on this pull request but we are blocked by:
* django-haystack/django-haystack#1863

**Comment by specialunderwear** [comment]
When the lint does not pass, try:
``make black``

**Comment by viggo-devries** [comment]
@cclauss thanks for this. Could you please also change the classifiers in the setup.py?

And I see you also work on django-haystack, any idea when the new version will be out?

Also I just updated django-oscar to work with haystack's generic views. If I had known I would have asked you to review it.
Maybe you can still give it a look? https://github.com/django-oscar/django-oscar/pull/4187

**Pull request closed without merging**
