### PR TITLE
Use unicode_literals everywhere. Drop all uses of u prefixes on strings.

### PR DESCRIPTION
**Pull request by solarissmoke**
Issues like #2176 are popping up because we don't consistently enforce unicode literals everywhere. Once you start digging, you can find the same issue in several other places. In some cases this has been locally fixed by using `u` prefixes on strings - I don't think this is a good approach.

Given that we are eventually moving to Python 3, this PR implements Django's [recommendation for porting](https://docs.djangoproject.com/en/1.11/topics/python3/#unicode-literals).

It's a pretty huge diff but there are only two changes:

1. Import `unicode_literals` everywhere for consistency.

2. Drop all `u` string prefixes.

### CODE REVIEW

**Comment by mvantellingen** [comment]
With Django 2.0 dropping 2.7 support i'm wondering how relevant this still is?

**Comment by solarissmoke** [comment]
Well, Django 1.11 is an LTS release, so in theory we should be supporting Python 2 until 2021...

**Comment by mvantellingen** [comment]
Ok understood. I think however we need to realise that adding unicode_literals to all modules can have some pretty big side-effects on Python 2. Accepting this PR might introduce a lot of new subtle bugs

**Comment by solarissmoke** [comment]
Yeah, I too am beginning to have second thoughts about this. I think it's probably too risky and test coverage is not sufficient to catch potential issues.

**Comment by sasha0** [comment]
We could limit this to only particular places where we spotted unicode-related issues, not to the whole project.

**Comment by solarissmoke** [comment]
> We could limit this to only particular places where we spotted unicode-related issues, not to the whole project.

I think this is also problematic - strings would be unicode or ascii depending on which file they were declared in, and you would have to check the top of the file to see why.

**Comment by sasha0** [comment]
Ok, what do you think would be the proper fix for the #2176?

**Comment by solarissmoke** [comment]
This is too risky it seems, so closing. We can fix individual issues on a case-by-case basis.

**Pull request closed without merging**
