### PR TITLE
Remove Django 1.6 support and some deprecated code

### PR DESCRIPTION
**Pull request by maikhoepfel**
Django 1.8 is knocking on the door, and it's unlikely that we'll get a release out before that is released. Furthermore, removing Django 1.6 support is desirable as supporting two migration frameworks and two app registry concepts has been a hassle, as is evident in the amount of code removed in this PR.

We will add Django 1.8 support in a separate PR.

### CODE REVIEW

**Comment by maikhoepfel** [comment]
A review would be appreciated. Ping @mbertheau @mvantellingen

**Comment by maikhoepfel** [comment]
I accidentally pushed https://github.com/django-oscar/django-oscar/commit/66f8201dd2d73ecb2bf9e198404f7a7037a9d1d2 onto master instead of this branch. Sorry.

**Comment by mbertheau** [comment]
Looks good upon reading. I hope I get a chance to try this out internally this week.

**Comment by mbertheau** [comment]
It runs well, no obvious problems :)

**Comment by maikhoepfel** [comment]
Cool, thanks for the review.

**Pull request merged**
