### PR TITLE
Do not allow basket line price become negative after discounts.

### PR DESCRIPTION
**Pull request by sasha0**
Refs #2773

### CODE REVIEW

**Comment by sasha0** [comment]
@pjstevns what do you think?

**Comment by pjstevns** [comment]
@sasha0 looks good to me

**Comment by pjstevns** [comment]
I added a PR against @sasha0 's PR which adds the tests

**Comment by sasha0** [comment]
@pjstevns thanks for implementing test.

@solarissmoke shall I mention about this change in the release notes?

**Comment by solarissmoke** [comment]
Added release note in https://github.com/django-oscar/django-oscar/commit/974eb2cde71b430ab82a03a62b656e99334734d8

**Pull request merged**
