### PR TITLE
1598/variant product alert

### LINKED ISSUE #1606: Email with '+' symbol not properly escaped in IndexView
If a user tries to checkout and then selects "create a new account" with an email address that contains a plus "+" sign, then the plus is silently removed from the email when the user is forwarded onto the registration form.

The fix is to urlquote the email in the success url for IndexView.

Pull request https://github.com/django-oscar/django-oscar/pull/1607

### PR DESCRIPTION
**Pull request by john-parton**
Fix #1606 

Hopefully pretty straightforward.

### CODE REVIEW

**Comment by john-parton** [comment]
Any updates on this? I thought it was a pretty straightforward fix.

**Comment by mvantellingen** [comment]
Looks good. We might need to document the new abstract_forms module in the changelog. 
Can you also update it against master? If not then i'll can take care of it.

Thanks!

**Comment by john-parton** [comment]
I think I see what I did. I created a separate pull request for the abstract_forms part: https://github.com/django-oscar/django-oscar/pull/1610

This was just supposed to be https://github.com/john-parton/django-oscar/commit/a92e72e1828f668cc852391e5e0265ffd6060525

Sorry, I'm still really new to git & github. (Still used to bzr)

I could create a new pull request for just the tiny change, and then you could review https://github.com/django-oscar/django-oscar/pull/1610 separately?

Let me know what I need to do.

Thanks.

**Comment by mvantellingen** [comment]
The easiest is to create a new PR with just the email fix. After that you can rebase #1610 on master and we can merge that one. :+

**Comment by john-parton** [comment]
Okay, I created the new PR: https://github.com/django-oscar/django-oscar/pull/1635

Sorry for the confusion. I'm trying to do some "easy" things to familiarize myself with github and oscar.

Thanks again!

**Pull request closed without merging**
