### PR TITLE
[WIP] Django 1.8 support

### PR DESCRIPTION
**Pull request by maikhoepfel**
This pull request is a work in progress. Don't merge yet.

I was bored on a train, so I built upon @mbertheau and @mvantellingen's work of getting Django 1.8 to work. This PR supersedes #1711, and addressed #1710.

The commits should be self-explanatory. The only real issue is that tables2 is still failing two of our tests. @mbertheau, could you have a look at that? I fear we need to bug it's maintainer for a release, but maybe there's an easy workaround.

### CODE REVIEW

**Comment by mbertheau** [comment]
I notified @bradleyayers about the django-tables2 django-1.8 issue: https://github.com/bradleyayers/django-tables2/commit/96bb04a2293122e100ef1ce1e747f3e4e7c5344a#commitcomment-10655089

**Comment by codeinthehole** [comment]
I think this issue is relevant too: https://github.com/django-oscar/django-oscar/issues/1708

**Comment by maikhoepfel** [comment]
FYI, `tables2` still fails with current master at https://github.com/bradleyayers/django-tables2/commit/679eb76daa3333556dbfdae4acd092e59a1c9b21.  I think we should make a PR and try to get it fixed. The maintainer(s) seem somewhat responsive.
#1708 seems like an easy fix.

**Comment by mvantellingen** [comment]
@maikhoepfel already fixed with https://github.com/bradleyayers/django-tables2/pull/245

**Comment by mvantellingen** [comment]
Turned out that #1708 wasn't related to Django 1.8. The same bug occurred with Django 1.7 on py3. Just fixed this in the master branch

**Pull request merged**
