### PR TITLE
When trackstock is off make price required

### PR DESCRIPTION
**Pull request by Wessellix**
fixes issue: https://github.com/django-oscar/django-oscar/issues/3913

### CODE REVIEW

**Comment by joeyjurjens** [comment]
I don't think this is the right solution. A better solution in my opinion would be showing "Unavailable" when there's no price entered. It doesn't really make sense to require a price when the product doesn't use "track stock", as it has nothing to do with each other, in this case price should also be required when the product does track stock.

@viggo-devries @specialunderwear your thoughts?

**Comment by specialunderwear** [comment]
I think the reason that price is not required, is that the strategy determines what the price should be. Most of the time that price will be taken from the stockrecord, but the source of the price could be anything, like:

from random import randint
randint(0, 4)
It might be you lucky day!

**Comment by viggo-devries** [comment]
I agree with @specialunderwear, maybe if there's not price it should say "Free"?

**Comment by specialunderwear** [comment]
> I agree with @specialunderwear, maybe if there's not price it should say "Free"?

no

**Pull request closed without merging**
