### PR TITLE
Prepare 3.0 alpha release.

### PR DESCRIPTION
**Pull request by solarissmoke**
- Update release notes for 3.0.
- Remove code that was deprecated in Oscar 2.1.

We should merge #3545 and #3546 before cutting the alpha, as those fix at least two issues with BS4.

### CODE REVIEW

**Comment by jwayodi** [comment]
This is not about the changes in this PR, but since we are here, these changes might be useful.

The second-last item under the section **What's new in Oscar 3.0?** should better reflect the fact that a `queryset` or `model_class` attribute must be defined, or alternatively the `get_queryset` must be overridden, otherwise an error will be raised.

In the section **Backwards incompatible changes**, in the sentence _The annotate_form_field template tag will now set the widget_type in the format used by Django 3.1: so no longer CheckboxField, but just checkbox._, _CheckboxField_ should be _CheckboxInput_.

In the first item under the section **Minor changes**, it might help to add a list of the models that have had a default-ordering definition added:
- `analytics.UserProductView`
- `analytics.UserSearch`
- `catalogue.Option`
- `communication.CommunicationEventType`
- `comunication.Email`
- `customer.ProductAlert`
- `offer.Range`
- `order.OrderDiscount`
- `order.OrderNote`
- `payment.Source`
- `payment.SourceType`
- `voucher.VoucherSet`
- `voucher.Voucher`
- `voucher.VoucherApplication`

There is no mention of models/fields that have had a database-index definition added, so that migrations can be generated for them in forked apps. A list would also help:
- `catalogue.Option.name`
- `communication.CommunicationEventType.name`
- `customer.ProductAlert.date_created`
- `payment.SourceType.name`
- `voucher.VoucherSet.date_created`
- `voucher.Voucher.date_created`
- `voucher.VoucherApplication.date_created`

**Comment by solarissmoke** [comment]
@jwayodi thanks, I've updated the notes to address your feedback.

**Review by jwayodi — APPROVED** [review]
This looks good.

**Comment by sasha0** [comment]
I'd add a bit more information into the commit messages, but overall looks good!

**Pull request merged**
