### PR TITLE
Fix sending direct messages.

### PR DESCRIPTION
**Pull request by michaelkuty**
Use same logic like has send_user_messages.

### CODE REVIEW

**Comment by sasha0** [comment]
Could you please refer to related issue? Thanks!

**Comment by michaelkuty** [comment]
Hi, thanks for checking PR, i havent any issue yet, but this fix sending messages when user does not exists, i use same behavior as is on line https://github.com/michaelkuty/django-oscar/blob/e6021815dbf38e2da1cc399a6267dc131dd10c72/src/oscar/apps/customer/utils.py#L55

When we has same templates/messages for non registered users then this method skips the message without any warning or exceptions

**Comment by sasha0** [comment]
Alright, could you please add test for this? Thanks.

**Comment by michaelkuty** [comment]
Ok working tests added.

**Comment by sasha0** [comment]
Thanks for the contribution!

**Pull request merged**
