### PR TITLE
Replace factories.create_product with factories.ProductFactory

### PR DESCRIPTION
**Pull request by john-parton**
Here's some initial work to close https://github.com/django-oscar/django-oscar/issues/1849

The plan is to replace all instances of `oscar.test.factories.create_product` with `oscar.test.factories.StandaloneProductFactory` or `oscar.test.factories.ParentProductFactory` as appropriate.

Right now, almost every test that involves `Product` ends up instantiating standalone products. Once the tests are cleaned up, I plan on adding some more tests cases to cover parent and child products.

### CODE REVIEW

**Comment by mvantellingen** [comment]
Hi John,

Thanks for all the work. I'll look into it better at a later time, but one initial point of feedback: I'd like to keep the `ProductFactory`. You can make `StandAloneProductFactory` a subclass of it. Also ProductFactory(structure='standalone') should be the same.

An other point is that you can set the stockrecord price in one go: `ProductFactory(stockrecords__price_excl_tax=x)`

**Comment by john-parton** [comment]
I left `ProductFactory` in as an alias for `StandaloneProductFactory`. My rationale is that the 3 structures of products are different enough that tests should be explicitly separated for clarity, and that `Product` is actually rather ambiguous. I would like to see the tests be clearer about what kind of product they're testing, be it a standalone product or parent-child pair.

Cool tip with the double underscore. Kind of illustrates what I mean, though. `ProductFactory(structure='parent', stockrecords__price_excl_tax=x)` doesn't make any sense (parents can't have stockrecords).

I'll defer to you on this, of course, but I thought I should elaborate a little.

**Comment by john-parton** [comment]
I also noticed that some tests, for instance `tests/unit/partner/import_tests.py` import a bunch of models directly, instead of using the `get_model` function.

```python
from oscar.apps.partner.importers import CatalogueImporter
from oscar.apps.partner.exceptions import ImportingError
from oscar.apps.catalogue.models import ProductClass, Product
from oscar.apps.partner.models import Partner
```

Should these use `get_model`?

**Comment by john-parton** [comment]
I found a bug after rewriting a test: https://github.com/django-oscar/django-oscar/issues/1860
I submitted a PR to fix the bug here: https://github.com/django-oscar/django-oscar/pull/1861

It's a tiny fix, but because it's not directly related to testing, I thought I should submit an issue/PR for it.

@mvantellingen Should I wait until the change is pulled into `master` or should I pull that into this branch as well?

Thanks.

**Comment by john-parton** [comment]
@mvantellingen I merged in master. Someone wrote some new tests using the old functional factories, so I had to update them to use the new classes. Really pretty easy, honestly.

**Comment by john-parton** [comment]
@mvantellingen Merged in master again. `TestScales.test_decimals` was broken. 

Basically, the weight attribute is a `float` (and there is no decimal type), so when the scale weighs 3 items that weight `0.3`, it ends up with `3 * Decimal(0.3)` which not the same as `Decimal('0.9')` due to float approximation. One solution is to quantize the decimal result with the `Decimal.quantize` method to round the weight to the nearest tenths (as I have done here). Another solution would be to use `self.assertAlmostEqual` instead, but I thought that was less clear.

**Comment by john-parton** [comment]
@mvantellingen Is there anything else I need to do with this one?

**Comment by john-parton** [comment]
@mvantellingen Is there any desire to get this merged?

Test writers have continued to use the `create_product` function instead of the class-based factories since Feb., which makes keeping this PR up-to-date very difficult. At this point, it might be easier to redo all of my changes against a fresh copy of master.

Thanks.

**Comment by solarissmoke** [comment]
Closing as there are too many conflicts. Need to start again or just make this change piecemeal as/when the relevant tests are updated.

**Pull request closed without merging**
