### PR TITLE
Replace insecure use of random() to generate random strings.

### PR DESCRIPTION
**Pull request by solarissmoke**

### CODE REVIEW

**Comment by sasha0** [comment]
Needs rebase, and as probably mention in the release docs.

**Comment by solarissmoke** [comment]
@sasha0 thanks, have rebased and added to release notes.

**Comment by sasha0** [comment]
What do you think about 1.6.1 version, rather then 2?

**Comment by solarissmoke** [comment]
Yeah, think we should backport to 1.6.x. I'll do that once this is merged to master.

**Pull request merged**
