### PR TITLE
Update dashboard to bootstrap 3

### PR DESCRIPTION
**Pull request by mvantellingen**
Use bootstrap 3 for the dashboard, this is based on the bootstrap3 branch.

This needs a good review before it is merged, and we might want to remove the bootstrap2 files from the repository.

TODO (by @mbertheau):
- [x] remove bootstrap2 files
- [x] remove bootstrap2 variables for `variables.less`
- [ ] test with a real world customized dashboard
- [x] resolve the partner dashboard issue (3d40611)
- [x] move customizations in `dashboard.less` to a separate file that's included in `dashboard.less`. That way implementations can have their own `dashboard.less` that includes a bootstrap3 `variables.less` that is customized and still reuse oscar styles that are now in `dashboard.less`

### CODE REVIEW

**Comment by mvantellingen** [comment]
Heya,

So i've squashed a number of commits and moved the whitespace changes to a separate commit.
@mbertheau This should solve are the (good) feedback you gave.

If there are no objects then I'll merge this next week.

**Comment by pwalsh** [comment]
Is this branch more or less ready for testing/use? I'm just about to port the dashboard for RTL support, and I'd rather do that on BS3. If so, I'll just work on this branch.

**Comment by mvantellingen** [comment]
@pwalsh: Yeah I think you should start from this branch then indeed :-)

**Comment by pwalsh** [comment]
@mvantellingen awesome.

**Comment by mbertheau** [comment]
@mvantellingen I cherry-picked the whitespace fixes and the path fix for `make css` onto master. I also moved the `dashboard_navigation` template tag call to the same commit that changes the syntax of that template tag.

I hope that I can test the meat of this branch internally this week.

Thanks for the cleanup, it looks really nice now :)

**Comment by mvantellingen** [comment]
@mbertheau I'm not really happy with the rewrite of my commit. Spent quite some time on this so please keep my commits intact.

Thanks :-)

**Comment by mbertheau** [comment]
@mvantellingen Sorry for that then. However I don't quite understand the problem. Could you elaborate?

**Comment by mbertheau** [comment]
Changed the author of the main commit to correctly credit @mvantellingen :)

**Comment by mbertheau** [comment]
I extracted the rest of the whitespace changes and bug fixes and cherry-picked them directly onto master. This branch / PR should now contain only the bootstrap3 porting.

@mvantellingen, do you remember why you didn't just use the form partial in the last commit?

**Comment by mvantellingen** [comment]
Nope no idea anymore.

**Comment by mbertheau** [comment]
I'm testing this branch in our project; however it takes a while to port our internal dashboard onto this branch, and I can dedicate only 1 or 2 hours every day to it. In the process I'll also look at the partner dashboard issue.

If someone else can test this branch in their oscar projects and report any bugs here that would be great.

**Comment by mvantellingen** [comment]
I've merged this after some more work on it. It was open for almost 6+ months and all feedback was taken care of.

If there are still any bugs left then let me know. We need to keep moving forward :-)

**Pull request merged**
