### PR TITLE
Update address book on billing address save

### LINKED ISSUE #1532: Saving a billing address doesn't update address book
It probably makes sense to add a billing address to a user's addressbook as part of checkout. We already do this for shipping addresses, but not for billing addresses. Should be a simple change.

### PR DESCRIPTION
**Pull request by sasha0**
Fixes #1532

### CODE REVIEW

**Comment by mvantellingen** [comment]
Looks good to me, could you also add a note to the changelog for 1.2?

**Comment by mvantellingen** [comment]
After looking more into this (need it myself actually), I think the address.num_orders isn't correct anymore. Since each order now increments two (or one and the same) address.num_order properties

**Comment by mvantellingen** [comment]
continued: perhaps we need to store the number of times an address is used as a billing address and the number of times it is used as a shipping address?

**Comment by sasha0** [comment]
@mvantellingen agreed. I'll make changes.

**Comment by sasha0** [comment]
@mvantellingen ok done. Please take a look.

**Comment by mvantellingen** [comment]
Looks good. Is it possible to a a property `num_orders` with a deprecation warning?

**Comment by sasha0** [comment]
@mvantellingen yep, done.

**Comment by digicase** [comment]
Do you think this pull request can be merged in soon? It looks like the needs more work requirement has been fulfilled by @sasha0 now.

**Comment by sasha0** [comment]
@digicase right, necessary changes were made accordingly to provided feedback, but let's ask @mvantellingen to review this.

**Comment by sasha0** [comment]
Moved release notes to the upcoming release 1.3.

**Comment by sasha0** [comment]
@digicase it's finally merged.

**Pull request merged**
