### PR TITLE
Updated offer.custom module to load models using get_model()

### LINKED ISSUE #2345: oscar.apps.offer.custom dependency on models prevents customization
The module `oscar.apps.offer.custom` imports the `Benefit` and `Condition` models directly instead of via `get_model()`. If either of these models is overridden by a forked version, this module cannot be imported.

The module should be updated to call `get_model()`.

### PR DESCRIPTION
**Pull request by clintonb**
This change ensures that the module can be loaded if models are customized in forked apps.

Fixes #2345

### CODE REVIEW

**Comment by clintonb** [comment]
@sasha0 @mvantellingen please review

**Comment by sasha0** [comment]
Thanks for the contribution!

**Comment by clintonb** [comment]
You're welcome!

**Comment by clintonb** [comment]
@sasha0 any idea when this will be released?

**Comment by sasha0** [comment]
@clintonb don't know exact date yet - we've planned to release 1.5 quite soon and had to postpone due to Django-Haystack incompatibility with Django 1.11. New release will be announced in the Oscar Slack channel.

**Pull request merged**
