### PR TITLE
Extended Product Option:

### PR DESCRIPTION
**Pull request by SummerSeaSun**
- default: value that is shown as form initial data
- sequence: allow user sort of options
- help_text
- choices: new form field type show a select as result of comma separated input

Affect setup: host/dashboard/catalogue/option/ and product detail view.

image

### CODE REVIEW

**Comment by solarissmoke** [comment]
Could you please clarify what the purpose of this change is - i.e., what functionality is being added/changed? Also note that we cannot change historic migrations in the way you have done here.

**Comment by SummerSeaSun** [comment]
Dear @solarissmoke , 

I've extended the  Option models related on Product, please look at the image of the product on the site that is attached: 

- now you can set a default value, that is shown as initial data on the form 
- sequence: allow user sort of options that are show to customer
- help_text: self explanatory
- choices: new form field type show a select as result of comma separated input

Affect setup: host/dashboard/catalogue/option/ and product detail view.
BR

**Comment by solarissmoke** [comment]
@SummerSeaSun the diff on this PR includes a very large number of changes that are completely unrelated to what you describe, or which are not acceptable (e.g., changes to historic migrations). You would need to fix those up before someone on the core team would be able to review this. Given the magnitude of the change required I'm going to close this PR for now - please feel free to reopen when you are able to refactor the code. You will likely have to do it on a fresh branch off of django-oscar's master, rather than off your own master branch which includes all sorts of other changes.

It may be also worth having a look at #3795 which is likely to get merged soon and addresses at least one of the same enhancements you have proposed.

**Comment by SummerSeaSun** [comment]
Please take a look at new pull requestest, only 3 files need some change.
https://github.com/django-oscar/django-oscar/pull/3859

**Pull request closed without merging**
