### PR TITLE
Removed username from comments in create_user methor in UserManager

### PR DESCRIPTION
**Pull request by DNX**
Removed a confusing typo

### CODE REVIEW

**Comment by DNX** [comment]
Why github merged two my pull requests in one? I want to track them separately.

**Comment by DNX** [comment]
For the commit 7e0e5c3 I opened another pull request as it regards different things.

**Comment by mvantellingen** [comment]
Also is it possible to open two separate PR's with only the relevant changes? We can close this one then

**Comment by sasha0** [comment]
Closed in favor of #2255, which is rebased version of this PR.

**Pull request closed without merging**
